import {
  Bot,
  Braces,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  Cable,
  ChartNoAxesCombined,
  Code2,
  Compass,
  FileCode2,
  Gauge,
  GitBranch,
  GraduationCap,
  MessagesSquare,
  MousePointerClick,
  Network,
  Palette,
  PanelTop,
  Plug,
  Rocket,
  Scale,
  Search,
  ShieldCheck,
  Shuffle,
  SlidersHorizontal,
  Sparkles,
  TerminalSquare,
  TextCursorInput,
  Unlock,
  Users,
  Workflow,
  type LucideIcon
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  Bot,
  Braces,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  Cable,
  ChartNoAxesCombined,
  Code2,
  Compass,
  FileCode2,
  Gauge,
  GitBranch,
  GraduationCap,
  MessagesSquare,
  MousePointerClick,
  Network,
  Palette,
  PanelTop,
  Plug,
  Rocket,
  Scale,
  Search,
  ShieldCheck,
  Shuffle,
  SlidersHorizontal,
  Sparkles,
  TerminalSquare,
  TextCursorInput,
  Unlock,
  Users,
  Workflow
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Lucide = icons[name] ?? Sparkles;
  return <Lucide className={className} aria-hidden="true" />;
}
